version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:30"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "container-base"
      - "security"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:40"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "ci"
      - "security"
    open-pull-requests-limit: 5
